
version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout

    # - run:
    #     name: Fix TLS
    #     command: |
    #       mkdir -p /etc/ssl/certs
    #       ln -s $NIX_SSL_CERT_FILE /etc/ssl/certs/ca-certificates.crt

    # - restore_cache:
    #     key: carnot-cache

      - run:
          name: Install Cachix
          command:
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                nix-env -iA cachix -f https://cachix.org/api/v1/install
              fi

      - run:
          name: Build
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                nix-build | cachix push carnot
              else
                nix-build --arg enableProfiling false --arg fast true
              fi

    # - save_cache:
    #     key: carnot-cache
    #     when: always
    #     paths:
    #       - /nix/store
