
version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - restore_cache:
          key: carnot-cache-{{ .Branch }}

      - run:
          name: Build
          command: |
            nix-shell --pure \
              --run "cabal configure; cabal build; nix-collect-garbage -d"

      - save_cache:
          key: carnot-cache-{{ .Branch }}
          when: always
          paths:
            - /nix/store
